name: update restart

on:
  push:

jobs:
  update_restart:
    runs-on: ubuntu-22.04
    steps:
      - name: update project and restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            PROJECT=${{ github.event.repository.name }}
            SERVICE=$PROJECT.service

            echo "Updating project: $PROJECT"
            cd $PROJECT
            git pull

            echo "Restarting service: $SERVICE"
            sudo systemctl restart $SERVICE
            sudo systemctl status $SERVICE --no-pager